# Generated by Django 4.1.7 on 2023-05-20 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chapter_chapter_id_alter_comment_comment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pythonchapter',
            fields=[
                ('novel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.novel')),
                ('last_crawled', models.DateTimeField(auto_now=True)),
                ('has_been_crawled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '小说爬取',
                'db_table': 'pythonchapter',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '种类'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '章节'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': '阅读历史'},
        ),
        migrations.AlterModelOptions(
            name='novel',
            options={'verbose_name_plural': '小说'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name_plural': '收藏评分'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '读者'},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='novel_id',
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.novel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='种类ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255, verbose_name='种类'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='章节ID'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_title',
            field=models.CharField(max_length=255, verbose_name='章节名'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=1023, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 8, 16, 28, tzinfo=datetime.timezone.utc), verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='history',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='历史记录ID'),
        ),
        migrations.AlterField(
            model_name='history',
            name='history_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 8, 16, 28, tzinfo=datetime.timezone.utc), verbose_name='历史时间'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.CharField(max_length=255, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='category',
            field=models.CharField(max_length=255, verbose_name='种类'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='cover',
            field=models.CharField(max_length=1023, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=models.CharField(max_length=1023, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='novel_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='小说ID'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='novel_title',
            field=models.CharField(max_length=255, verbose_name='小说名'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='state',
            field=models.CharField(max_length=20, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='score',
            name='favorite',
            field=models.IntegerField(null=True, verbose_name='收藏'),
        ),
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=255, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, verbose_name='用户名'),
        ),
    ]
