# Generated by Django 4.1.7 on 2023-05-20 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pythonchapter_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='pa_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='novel',
            name='pa_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 12, 31, 18, tzinfo=datetime.timezone.utc), verbose_name='爬取时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 12, 31, 18, tzinfo=datetime.timezone.utc), verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='history',
            name='history_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 12, 31, 18, tzinfo=datetime.timezone.utc), verbose_name='历史时间'),
        ),
        migrations.DeleteModel(
            name='Pythonchapter',
        ),
    ]
