# Generated by Django 4.1.7 on 2023-05-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_comment_created_time_alter_cover_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='history',
            name='history_time',
            field=models.DateTimeField(auto_now=True, verbose_name='历史时间'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_time',
            field=models.DateTimeField(auto_now=True, verbose_name='邮件时间'),
        ),
    ]
