# Generated by Django 4.1.7 on 2023-05-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='pa_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='爬取时间'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=8, null=True, verbose_name='评分'),
        ),
    ]
